version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - YAHOO_FINANCE_API_KEY=${YAHOO_FINANCE_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # Development service with hot reload
  portfolio-analyzer-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    stdin_open: true
    tty: true
