version: '3.8'

services:
  portfolio-analyzer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    stdin_open: true
    tty: true

  # Development service with hot reload
  portfolio-analyzer-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    stdin_open: true
    tty: true
