version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      # Add any environment variables required by your Next.js app here
      # For example:
      # - NEXT_PUBLIC_API_URL=http://localhost:3000/api

  # Development service with hot reload
  portfolio-analyzer-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    stdin_open: true
    tty: true
